### ISSUE TITLE
Dependant on orchestral/config?

### ISSUE THREAD

**Issue by Thatplayer** [orchestral/memory#22]
Hello, I'm trying to use this package as in Laravel 5 and have come across a few problems.

On a fresh Laravel 5 install, after adding the service providers and aliases and running the migration, any attempts to use Memory end with an error:

    Illuminate\Database\QueryException with message 'SQLSTATE[HY000]: General error: 1 no such table: default (SQL: select * from "default")'

Installing orchestral/config seems to fix this, though config publishing still doesn't work

**Comment by Thatplayer** [comment]
Thanks for the quick fix!

But it looks like it's still trying to access the wrong configurations 

https://github.com/orchestral/memory/blob/master/src/MemoryManager.php#L30

**Comment by crynobone** [comment]
Ah bummer, forgot about that part. Will fix in a minute.

**Comment by crynobone** [comment]
Can you change to `"orchestra/memory": "3.0.*@dev"` and test 56b76de

**Comment by Thatplayer** [comment]
Seems to be working fine, thanks!

**Comment by crynobone** [comment]
Tagged with `v3.0.3`.
