### ISSUE TITLE
[3.2] Calling `finish()` doesn't remove keys

### ISSUE THREAD

**Issue by stevebauman** [orchestral/memory#23]
The finish method doesn't remove any keys that were removed in the items array, it only checks for new keys:

https://github.com/orchestral/memory/blob/master/src/DatabaseHandler.php#L46

This is linked to the orchestra support PR: https://github.com/orchestral/support/pull/41

**Comment by crynobone** [comment]
Can you check the latest push on memory.

**Comment by crynobone** [comment]
@stevebauman did you manage to check the latest commits?

**Comment by stevebauman** [comment]
Going to try this now, apologies for the late reply!
