### ISSUE TITLE
Fail to publish configuration

### ISSUE THREAD

**Issue by dickylhf** [orchestral/memory#28]
- Package Version: v4.0.0
- Laravel Version: 6.18.36
- PHP Version: 7.3.13

### Description:
Throw error (Unable to locate publishable resources.) when running command php artisan vendor:publish --provider="Orchestra\Memory\MemoryServiceProvider".

### Steps To Reproduce:
Run php artisan vendor:publish --provider="Orchestra\Memory\MemoryServiceProvider".

**Comment by crynobone** [comment]
Sorry but `orchestra/memory` doesn't support Laravel Package Discovery.

You need to follow the installation steps first before trying to publish the command.

![Screenshot 2020-08-29 at 9 52 00 AM](https://user-images.githubusercontent.com/172966/91625881-6df46980-e9dd-11ea-9b18-a54b3108490e.png)
